/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : task_template_list.c
**     Project     : FSFK_K64F
**     Processor   : MK64FN1M0VLL12
**     Version     : Component 01.110, Driver 01.00, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-11-26, 15:07, # CodeGen: 19
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file task_template_list.c                                                  
** @version 01.00
*/         
/*!
**  @addtogroup task_template_list_module task_template_list module documentation
**  @{
*/         

#include "task_template_list.h"
#include "mqx_tasks.h"
  
#define TASK_TEMPLATE_LIST_END         {0, 0, 0, 0, 0, 0, 0}

/* MQX task template list */
const TASK_TEMPLATE_STRUCT MQX_template_list[] =
{
  /* Task: RdSensData */
  {
  /* Task number                      */  RDSENSDATA_TASK,
  /* Entry point                      */  (TASK_FPTR)RdSensData_task,
  /* Stack size                       */  RDSENSDATA_TASK_STACK_SIZE,
  /* Task priority                    */  8U,
  /* Task name                        */  "rdsensdata",
  /* Task attributes                  */  (MQX_AUTO_START_TASK | MQX_FLOATING_POINT_TASK),
  /* Task parameter                   */  (uint32_t)(0)
  },
  /* Task: Fusion */
  {
  /* Task number                      */  FUSION_TASK,
  /* Entry point                      */  (TASK_FPTR)Fusion_task,
  /* Stack size                       */  FUSION_TASK_STACK_SIZE,
  /* Task priority                    */  9U,
  /* Task name                        */  "fusion",
  /* Task attributes                  */  (MQX_FLOATING_POINT_TASK),
  /* Task parameter                   */  (uint32_t)(0)
  },
  /* Task: MagCal */
  {
  /* Task number                      */  MAGCAL_TASK,
  /* Entry point                      */  (TASK_FPTR)MagCal_task,
  /* Stack size                       */  MAGCAL_TASK_STACK_SIZE,
  /* Task priority                    */  10U,
  /* Task name                        */  "magcal",
  /* Task attributes                  */  (MQX_FLOATING_POINT_TASK),
  /* Task parameter                   */  (uint32_t)(0)
  },
  TASK_TEMPLATE_LIST_END
};

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
