/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : FMSTR1.c
**     Project     : robit_drone_rc
**     Processor   : MK64FN1M0VLL12
**     Component   : FreeMaster
**     Version     : Component 01.129, Driver 01.06, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-11-24, 21:40, # CodeGen: 7
**     Abstract    :
**          This component encapsulates the FreeMASTER driver. The FreeMASTER
**          driver implements all the features necessary to establish a communication
**          with the FreeMASTER visualization tool.
**     Settings    :
**          Component name                                 : FMSTR1
**          Version                                        : 1.9
**          Interrupt mode                                 : Mixed interrupt and polling mode
**          Device                                         : SCI
**            Init_UART                                    : Init_UART_VAR0
**          Oscilloscope                                   : Disabled
**          Recorder                                       : Disabled
**          Application command                            : Disabled
**          Target-side addressing                         : Disabled
**          Pipes                                          : Disabled
**          Initialization                                 : 
**            Read/write memory commands                   : Enabled
**              Read memory                                : Enabled
**              Write memory                               : Enabled
**              Write memory bits                          : Enabled
**            Read/write variable commands                 : Disabled
**            Data buffer length                           : 0
**            FIFO receiver queue length                   : 32
**            Interrupt callback function                  : 
**     Contents    :
**         Poll - void FMSTR1_Poll(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file FMSTR1.c
** @version 01.06
** @brief
**          This component encapsulates the FreeMASTER driver. The FreeMASTER
**          driver implements all the features necessary to establish a communication
**          with the FreeMASTER visualization tool.
*/         
/*!
**  @addtogroup FMSTR1_module FMSTR1 module documentation
**  @{
*/         

/* MODULE FMSTR1. */


#include "FMSTR1.h"

/*
** ===================================================================
**     Method      :  FMSTR1_Init (component FreeMaster)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/*
void FMSTR1_Init(void)

**  This method is implemented as a macro. See FMSTR1.h file.  **

*/
/*
** ===================================================================
**     Method      :  FMSTR1_Poll (component FreeMaster)
**     Description :
**         In the poll-driven or short interrupt modes, this function
**         handles the protocol decoding and execution. In the
**         poll-driven mode, this function also handles the SCI
**         communication. In the long interrupt mode, this function
**         compiles as an empty function and may still be called.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void FMSTR1_Poll(void)

**  This method is implemented as a macro. See FMSTR1.h file.  **

*/
/*
** ===================================================================
**     Method      :  FMSTR1_Isr (component FreeMaster)
**
**     Description :
**         Main SCI/JTAG Interrupt handler call. This Interrupt Service 
**         Routine handles the interrupts for the FreeMASTER driver.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/*
void FMSTR1_Isr(void)

**  This method is implemented as a macro. See FMSTR1.h file.  **

*/
/* END FMSTR1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
