/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : freemaster_cfggen.h
**     Project     : robit_drone_rc
**     Processor   : MK64FN1M0VLL12
**     Version     : Component 01.129, Driver 01.06, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-11-24, 21:40, # CodeGen: 7
**     Abstract    :
**          This component encapsulates the FreeMASTER driver. The FreeMASTER
**          driver implements all the features necessary to establish a communication
**          with the FreeMASTER visualization tool.
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file freemaster_cfggen.h                                                  
** @version 01.06
** @brief
**          This component encapsulates the FreeMASTER driver. The FreeMASTER
**          driver implements all the features necessary to establish a communication
**          with the FreeMASTER visualization tool.
*/         
/*!
**  @addtogroup freemaster_cfggen_module freemaster_cfggen module documentation
**  @{
*/         

/* Select interrupt or poll-driven serial communication */
#define FMSTR_LONG_INTR         0x00
#define FMSTR_SHORT_INTR        0x01   /* SCI FIFO-queuing done in interrupt */
#define FMSTR_POLL_DRIVEN       0x00

/* SCI communication */
#define FMSTR_DISABLE           0x00   /* FreeMASTER is enabled */
#define FMSTR_USE_SCI           0x01   /* Use SCI interface */
#define FMSTR_SCI_BASE          0x4006A000 /* SCI Base address */
#define FMSTR_USE_MSCAN         0x00   /* Disables MSCAN interface */
#define FMSTR_USE_FLEXCAN       0x00   /* Disables FLEXCAN interface */
#define FMSTR_USE_USB_CDC       0x00   /* Disables USB CDC communication interface */
#define FMSTR_USE_PDBDM         0x00   /* Disables Packet Driven BDM communication interface */

/* FreeMASTER communication buffer */
#define FMSTR_COMM_BUFFER_SIZE  0x00   /* Input/output communication buffer size */
#define FMSTR_COMM_RQUEUE_SIZE  0x20   /* Receive FIFO queue size (use with FMSTR_SHORT_INTR only) */

/* Application command support */
//#define FMSTR_USE_APPCMD        0x00   /* Application commands support disabled */
//#define FMSTR_APPCMD_BUFF_SIZE  0x10   /* Application command buffer size */
//#define FMSTR_MAX_APPCMD_CALLS  0x00   /* How many app.cmd callbacks? (0=disable) */

/* Oscilloscope support */
//#define FMSTR_USE_SCOPE         0x00   /* Scope disabled */
//#define FMSTR_MAX_SCOPE_VARS    8      /* Max. number of scope variables (2..8) */

/* Recorder support */
//#define FMSTR_USE_RECORDER      0x00   /* Recorder support disabled */
//#define FMSTR_REC_BUFF_SIZE     256    /* Recorder buffer size */
//#define FMSTR_REC_TIMEBASE      FMSTR_REC_BASE_SECONDS(0) /* Recorder timebase */

/* Target-side addressing support */
//#define FMSTR_USE_TSA           0x00   /* Disable TSA functionality */
//#define FMSTR_USE_TSA_SAFETY    0x00   /* Disable access to TSA variables only */
//#define FMSTR_USE_TSA_INROM     0x00   /* TSA tables are not declared as const */
#define FMSTR_GEN_TSA_LIST()           /* Generated TSA tables */

/* Pipes support */
//#define FMSTR_USE_PIPES         0x00   /* Disable pipes functionality */

//#define FMSTR_USE_READMEM       0x01   /* Enable read memory commands */
//#define FMSTR_USE_WRITEMEM      0x01   /* Enable write memory commands */
//#define FMSTR_USE_WRITEMEMMASK  0x01   /* Enable masked write memory commands */

//#define FMSTR_USE_READVAR       0x00   /* Disable read variable fast commands */
//#define FMSTR_USE_WRITEVAR      0x00   /* Disable write variable fast commands */
//#define FMSTR_USE_WRITEVARMASK  0x00   /* Disable write variable bits fast commands */

/* SFIO support */
//#define FMSTR_USE_SFIO          0x00   /* SFIO support disabled */

//#define FMSTR_ISR_CALLBACK           /* Application callback function in the isr routine */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
